IF
	Global("BD_POINT6","BD0114",4)  // Spider Cave: Rhinoceros Beetle appeared
	StateCheck("BDBEETRH",STATE_REALLY_DEAD)  // Rhinoceros Beetle
	Global("WNOPHY_BD_BEETLE","BD0114",0)  
	!GlobalTimerNotExpired("BD_TIMER_RHINOTALK","BD0114")  
	IfValidForPartyDialog("WNOPHY")  
THEN
	RESPONSE #100
		DisplayStringHead("WNOPHY",~This is incredibly gross. So incredibly gross...~)
		SetGlobal("WNOPHY_BD_BEETLE","BD0114",1)  
END